language: ruby
rvm: 2.5.1
env:
  global:
    - CC_TEST_REPORTER_ID=943d1f35a9019cfc884b0a99a26020c95b1e5b46f20cb63d1fc05bbebab0772a
    - RAILS_ENV=test
services: postgresql
bundler_args: "--without production -j4"
cache: bundler
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script: bundle exec rake test
after_script:
  - pwd
  - find coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: heroku
  api_key:
    secure: "gffDSKMcoKpBmektjBnb/AIeGCjEfyiIJHZRYg49ZYaBssb23Zp2kAwDinh9Hse9XbAm1dE8i6YtZfJX35FnI4HHYp8FqWbr8cVs1jxC2ebOsXs0gabMg7GFwTN7iUiSLu/Fd046S97ezgcLJ0ADmHyFIYirGOH5zTUeuSUWce2B/+dt3L5DFbJPEPKTfguCzZXiqsIaC7UwyRppnQ2amN4S1hijSKC8aOO+vCWQzbCeGKiEdYue9RqycQX2lVnYNFi+vK3p8k4rsE2VFBStjpbPu2OrlWzs/h2mAvRAlWHx79CTtFXSAZYLBJy/PfSu6rjuUgtSSngFUrJlJSHAxXV1qlnCEcj6VRotEW6awThRDK/88JhC6gUvRQ3oL/yoxoqxeNAzrCG3bGs4qTv+9+bzA1WUdSs9XQVVOJ69WA3v01P47FK5HxY+zheFdau5hkPDiRHau+tVQFrIcTHt9gAeh+fceei4OHHBmg9x5cIJFGepmLW4bbpAjbkhC1V8LPOtBBvSanhP/inmbLkqs6itHPsmq3gvqoMaxmrIWt/mE4dVH1k5nXYKPxD1gkHhtMV8HrHAihwlh+EtT3XHMyAPwxo60ubqYETp5cnNJ082HAgd9qzaboyJ9h9GhvdbgJlYsEMtWj5PjWZ1gepCnFCySlZuV4S6mXqZTjveqiI="
  app: ydmsample-201901-stage
  on:
    repo: yosi-q/ydmsample-201901
  run:
    - bundle exec rake db:migrate
notifications:
  slack:
    rooms:
      - secure: "BZFjOAr2vEjzRCeNQCe0WkSVIeH1X0WCI511zkQAFf4+NlHKhwC4s87HDw6nIPIU09gU9vvm/7PCW88Xobsq/2emCyQ2lJl3dnRmzgAM/A1UakdRzG/TLKrvvRsChh0RRAdu4itOpxcznnSPXCfoGENgwL/XjA/pZET7T0XU7/romZ9DvcyOZMJ8CRRpHmiYePlgLI3aB3kx/tccKMLeo1wWcnYudA2NXZtJKaOB54/UWe8MSy6L902MNHri7hzAGbSCqvzNUYrCs2U1qYSlF0gpfbrIPNWDYex90i6qwxjTF/cAzlmfujSPpGYVCaDcJ+P3R/LJWKKDhvEGjA87uBNC+vFdwhl2jwRY5XW+fFcGTQrPDsvVzvu6hC+5lmFkKC0d3uvYchjwvEAZVEORdNnDS+MHiQYxd8hUVTowrwES4zGI4+4viRQyN0+La09jIeZ61tMBPYrSAhz/yNj9JcvSdRHs9a1lZ7fG8somB6ceZadTN6gOjIsQWFsfTfzNFPN+wPZRG90qJMejlZIGywk+Rbkd0KnGUUR0kGdW1jE4LIKqtbcBq29YtOh1iEnSCbwb9d/tH7Ne3QvWmNvd2iZHx/dKX6XS/RDPa6W5cM5VoF+4tLZ5WmXRa/2omK2V+6I3zeW2WK2uscpwOWlN+jEmejd8AtlYCuQLBJf3sks="
    on_success: always
    on_failure: always
    on_pull_requests: true
